/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class ConfirmExit extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmExit
     */
    public ConfirmExit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        confirmText = new javax.swing.JLabel();
        buttonCancel = new javax.swing.JPanel();
        buttonCancelText = new javax.swing.JLabel();
        buttonConfirm = new javax.swing.JPanel();
        buttonConfirmText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(240, 240, 240));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirmText.setFont(new java.awt.Font("agave Nerd Font", 1, 18)); // NOI18N
        confirmText.setForeground(new java.awt.Color(213, 13, 13));
        confirmText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmText.setText("¿Está seguro de salir?");
        background.add(confirmText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 40));

        buttonCancel.setBackground(new java.awt.Color(46, 125, 50));

        buttonCancelText.setFont(new java.awt.Font("agave Nerd Font", 0, 14)); // NOI18N
        buttonCancelText.setForeground(new java.awt.Color(255, 255, 255));
        buttonCancelText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonCancelText.setText("CANCELAR");
        buttonCancelText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonCancelTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonCancelTextMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonCancelTextMousePressed(evt);
            }
        });

        javax.swing.GroupLayout buttonCancelLayout = new javax.swing.GroupLayout(buttonCancel);
        buttonCancel.setLayout(buttonCancelLayout);
        buttonCancelLayout.setHorizontalGroup(
            buttonCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonCancelText, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        buttonCancelLayout.setVerticalGroup(
            buttonCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonCancelText, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        background.add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 160, 40));

        buttonConfirm.setBackground(new java.awt.Color(46, 125, 50));

        buttonConfirmText.setFont(new java.awt.Font("agave Nerd Font", 0, 14)); // NOI18N
        buttonConfirmText.setForeground(new java.awt.Color(255, 255, 255));
        buttonConfirmText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonConfirmText.setText("CONFIRMAR");
        buttonConfirmText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonConfirmTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonConfirmTextMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonConfirmTextMousePressed(evt);
            }
        });

        javax.swing.GroupLayout buttonConfirmLayout = new javax.swing.GroupLayout(buttonConfirm);
        buttonConfirm.setLayout(buttonConfirmLayout);
        buttonConfirmLayout.setHorizontalGroup(
            buttonConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonConfirmText, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        buttonConfirmLayout.setVerticalGroup(
            buttonConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonConfirmText, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        background.add(buttonConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConfirmTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonConfirmTextMouseEntered
        buttonConfirm.setBackground(new Color(0, 80, 5));
        buttonConfirm.setToolTipText("Confirmar");
    }//GEN-LAST:event_buttonConfirmTextMouseEntered

    private void buttonConfirmTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonConfirmTextMouseExited
        buttonConfirm.setBackground(new Color(46, 125, 50));
    }//GEN-LAST:event_buttonConfirmTextMouseExited

    private void buttonConfirmTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonConfirmTextMousePressed
        
        Welcome welcome = new Welcome();
        welcome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonConfirmTextMousePressed

    private void buttonCancelTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCancelTextMouseEntered
        buttonCancel.setBackground(new Color(0, 80, 5));
        buttonCancel.setToolTipText("Cancelar");
    }//GEN-LAST:event_buttonCancelTextMouseEntered

    private void buttonCancelTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCancelTextMouseExited
        buttonConfirm.setBackground(new Color(46, 125, 50));
    }//GEN-LAST:event_buttonCancelTextMouseExited

    private void buttonCancelTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCancelTextMousePressed
        this.dispose();
    }//GEN-LAST:event_buttonCancelTextMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmExit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmExit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmExit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmExit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmExit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel buttonCancel;
    private javax.swing.JLabel buttonCancelText;
    private javax.swing.JPanel buttonConfirm;
    private javax.swing.JLabel buttonConfirmText;
    private javax.swing.JLabel confirmText;
    // End of variables declaration//GEN-END:variables
}
