/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class ConfirmSignUp extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmSignUp
     */
    public ConfirmSignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        confirmText = new javax.swing.JLabel();
        buttonConfirm = new javax.swing.JPanel();
        buttonConfirmText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(418, 161));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirmText.setFont(new java.awt.Font("agave Nerd Font", 1, 16)); // NOI18N
        confirmText.setForeground(new java.awt.Color(46, 175, 41));
        confirmText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmText.setText("Usuario registrado, dirigiendo a Iniciar Sesión");
        jPanel1.add(confirmText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 400, 40));

        buttonConfirm.setBackground(new java.awt.Color(46, 125, 50));

        buttonConfirmText.setFont(new java.awt.Font("agave Nerd Font", 0, 14)); // NOI18N
        buttonConfirmText.setForeground(new java.awt.Color(255, 255, 255));
        buttonConfirmText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonConfirmText.setText("ACEPTAR");
        buttonConfirmText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonConfirmTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonConfirmTextMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonConfirmTextMousePressed(evt);
            }
        });

        javax.swing.GroupLayout buttonConfirmLayout = new javax.swing.GroupLayout(buttonConfirm);
        buttonConfirm.setLayout(buttonConfirmLayout);
        buttonConfirmLayout.setHorizontalGroup(
            buttonConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonConfirmText, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        buttonConfirmLayout.setVerticalGroup(
            buttonConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonConfirmText, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(buttonConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConfirmTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonConfirmTextMouseEntered
        buttonConfirm.setBackground(new Color(0, 80, 5));
        buttonConfirm.setToolTipText("Confirmar");
    }//GEN-LAST:event_buttonConfirmTextMouseEntered

    private void buttonConfirmTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonConfirmTextMouseExited
        buttonConfirm.setBackground(new Color(46, 125, 50));
    }//GEN-LAST:event_buttonConfirmTextMouseExited

    private void buttonConfirmTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonConfirmTextMousePressed

        SignIn signin = new SignIn();
        signin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonConfirmTextMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonConfirm;
    private javax.swing.JLabel buttonConfirmText;
    private javax.swing.JLabel confirmText;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
