package Interfaces;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javaproject.parking.connectionDB;

public class SignIn extends javax.swing.JFrame {

    int xMouse, yMouse;
    
    connectionDB connectionV;

    
    public SignIn() {
        initComponents();
        
        connectionV = new connectionDB("parking_son");
        connectionV.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        imageBackground = new javax.swing.JLabel();
        signInText = new javax.swing.JLabel();
        userText = new javax.swing.JLabel();
        inputUserSignIn = new javax.swing.JTextField();
        separator = new javax.swing.JSeparator();
        passText1 = new javax.swing.JLabel();
        separator1 = new javax.swing.JSeparator();
        inputPassSignIn = new javax.swing.JPasswordField();
        signInButton = new javax.swing.JPanel();
        signInLabel = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        exitButton = new javax.swing.JPanel();
        exitTextX = new javax.swing.JLabel();
        textSignUp = new javax.swing.JLabel();
        textWarning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setForeground(new java.awt.Color(0, 0, 0));
        backgroundPanel.setMinimumSize(new java.awt.Dimension(895, 573));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("PARKING SON'S");
        backgroundPanel.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 250, 80));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LogoEdited.png"))); // NOI18N
        logo.setText("jLabel2");
        backgroundPanel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 240, 210));

        imageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/parking image edited_1.png"))); // NOI18N
        backgroundPanel.add(imageBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 580));

        signInText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        signInText.setForeground(new java.awt.Color(0, 0, 0));
        signInText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signInText.setText("INICIAR SESIÓN");
        signInText.setToolTipText("");
        backgroundPanel.add(signInText, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        userText.setFont(new java.awt.Font("agave Nerd Font", 0, 14)); // NOI18N
        userText.setForeground(new java.awt.Color(0, 0, 0));
        userText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userText.setText("USUARIO");
        backgroundPanel.add(userText, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        inputUserSignIn.setBackground(new java.awt.Color(255, 255, 255));
        inputUserSignIn.setFont(new java.awt.Font("mononoki NF", 0, 12)); // NOI18N
        inputUserSignIn.setForeground(new java.awt.Color(204, 204, 204));
        inputUserSignIn.setText("Ingrese su nombre de usuario");
        inputUserSignIn.setBorder(null);
        inputUserSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputUserSignInMousePressed(evt);
            }
        });
        backgroundPanel.add(inputUserSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 440, 40));

        separator.setBackground(new java.awt.Color(0, 0, 0));
        separator.setForeground(new java.awt.Color(0, 0, 0));
        backgroundPanel.add(separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 440, -1));

        passText1.setFont(new java.awt.Font("agave Nerd Font", 0, 14)); // NOI18N
        passText1.setForeground(new java.awt.Color(0, 0, 0));
        passText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passText1.setText("CONTRASEÑA");
        backgroundPanel.add(passText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));

        separator1.setBackground(new java.awt.Color(0, 0, 0));
        separator1.setForeground(new java.awt.Color(0, 0, 0));
        backgroundPanel.add(separator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 440, -1));

        inputPassSignIn.setBackground(new java.awt.Color(255, 255, 255));
        inputPassSignIn.setForeground(new java.awt.Color(204, 204, 204));
        inputPassSignIn.setText("*************");
        inputPassSignIn.setBorder(null);
        inputPassSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputPassSignInMousePressed(evt);
            }
        });
        backgroundPanel.add(inputPassSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 440, 40));

        signInButton.setBackground(new java.awt.Color(46, 125, 50));
        signInButton.setForeground(new java.awt.Color(255, 255, 255));
        signInButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        signInLabel.setBackground(new java.awt.Color(46, 125, 50));
        signInLabel.setFont(new java.awt.Font("agave Nerd Font", 1, 14)); // NOI18N
        signInLabel.setForeground(new java.awt.Color(255, 255, 255));
        signInLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signInLabel.setText("ENTRAR");
        signInLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signInLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signInLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signInLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout signInButtonLayout = new javax.swing.GroupLayout(signInButton);
        signInButton.setLayout(signInButtonLayout);
        signInButtonLayout.setHorizontalGroup(
            signInButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signInLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        signInButtonLayout.setVerticalGroup(
            signInButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signInLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        backgroundPanel.add(signInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 232, -1));

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerPanelMouseDragged(evt);
            }
        });
        headerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerPanelMousePressed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(255, 255, 255));
        exitButton.setPreferredSize(new java.awt.Dimension(35, 20));

        exitTextX.setFont(new java.awt.Font("agave Nerd Font", 1, 20)); // NOI18N
        exitTextX.setForeground(new java.awt.Color(0, 0, 0));
        exitTextX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTextX.setText("X");
        exitTextX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTextX.setPreferredSize(new java.awt.Dimension(35, 20));
        exitTextX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTextXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTextXMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitTextXMousePressed(evt);
            }
        });

        javax.swing.GroupLayout exitButtonLayout = new javax.swing.GroupLayout(exitButton);
        exitButton.setLayout(exitButtonLayout);
        exitButtonLayout.setHorizontalGroup(
            exitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitButtonLayout.createSequentialGroup()
                .addComponent(exitTextX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exitButtonLayout.setVerticalGroup(
            exitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitButtonLayout.createSequentialGroup()
                .addComponent(exitTextX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(879, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        backgroundPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        textSignUp.setText("¿Aún no tienes una cuenta?");
        textSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textSignUpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textSignUpMouseExited(evt);
            }
        });
        backgroundPanel.add(textSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 330, -1, -1));

        textWarning.setFont(new java.awt.Font("agave Nerd Font", 0, 12)); // NOI18N
        textWarning.setForeground(new java.awt.Color(255, 51, 51));
        backgroundPanel.add(textWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 440, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void headerPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerPanelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerPanelMousePressed

    private void headerPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerPanelMouseDragged
        
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerPanelMouseDragged

    private void exitTextXMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextXMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitTextXMousePressed

    private void exitTextXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextXMouseEntered
       
        exitButton.setBackground(new Color(254, 45,45));
        exitTextX.setForeground(Color.white);
    }//GEN-LAST:event_exitTextXMouseEntered

    private void exitTextXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextXMouseExited
        exitButton.setBackground(Color.white);
        exitTextX.setForeground(Color.BLACK);
    }//GEN-LAST:event_exitTextXMouseExited

    private void signInLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInLabelMouseEntered
        signInButton.setBackground(new Color(0, 80, 5));
    }//GEN-LAST:event_signInLabelMouseEntered

    private void signInLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInLabelMouseExited
        signInButton.setBackground(new Color(46, 125, 50));
    }//GEN-LAST:event_signInLabelMouseExited

    private void signInLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInLabelMousePressed
        
        try {
            String user = inputUserSignIn.getText();
            String pass = String.valueOf(inputPassSignIn.getPassword());

            String query = "SELECT * from usuarios WHERE usuario ='" + user + "' and contraseña= '"+ pass +"'";

            Statement st = connectionV.connect().createStatement();
            ResultSet rs = st.executeQuery(query);

            if(rs.next()) {
                Home home = new Home();
                home.setVisible(true);
                this.dispose();

            } else if(user.equals("Ingrese su nombre de usuario") || pass.equals("*************")) {
                textWarning.setText("Por favor ingrese un nombre de usuario y contraseña.");

                separator.setForeground(Color.red);
                separator1.setForeground(Color.red);
                separator.setBackground(Color.red);
                separator1.setBackground(Color.red);
            } else {
                textWarning.setText("Usuario o contraseña incorrectos.");

                separator.setForeground(Color.red);
                separator1.setForeground(Color.red);
                separator.setBackground(Color.red);
                separator1.setBackground(Color.red);

                inputUserSignIn.setText("Ingrese su nombre de usuario");
                inputPassSignIn.setText("*************");

                inputUserSignIn.setForeground(new Color(204, 204, 204));
                inputPassSignIn.setForeground(new Color(204, 204, 204));
            }
            
        } catch(SQLException e) {
            System.err.println("No se ha podido realizar la consulta a la base de datos.");
        }
    }//GEN-LAST:event_signInLabelMousePressed

    private void inputUserSignInMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputUserSignInMousePressed
        if(inputUserSignIn.getText().equals("Ingrese su nombre de usuario")) {
            inputUserSignIn.setText("");
            inputUserSignIn.setForeground(Color.black);
        }
        
        if(String.valueOf(inputPassSignIn.getPassword()).isEmpty()) {
            inputPassSignIn.setText("*************");
            inputPassSignIn.setForeground(new Color(204,204,204));
        }
        
    }//GEN-LAST:event_inputUserSignInMousePressed

    private void inputPassSignInMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputPassSignInMousePressed
       
        if(String.valueOf(inputPassSignIn.getPassword()).equals("*************")) {
            inputPassSignIn.setText("");
            inputPassSignIn.setForeground(Color.black);
        }
        
        if(inputUserSignIn.getText().isEmpty()) {
        inputUserSignIn.setText("Ingrese su nombre de usuario");
        inputUserSignIn.setForeground(new Color(204,204,204));
        }
        
        
    }//GEN-LAST:event_inputPassSignInMousePressed

    private void textSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textSignUpMouseEntered
        textSignUp.setForeground(new Color(100,100,100));
    }//GEN-LAST:event_textSignUpMouseEntered

    private void textSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textSignUpMouseExited
        textSignUp.setForeground(new Color(187,187, 187));
    }//GEN-LAST:event_textSignUpMouseExited

    private void textSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textSignUpMouseClicked
        // TODO add your handling code here:
        SignUp signup = new SignUp();
        signup.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_textSignUpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel exitButton;
    private javax.swing.JLabel exitTextX;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel imageBackground;
    private javax.swing.JPasswordField inputPassSignIn;
    private javax.swing.JTextField inputUserSignIn;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel name;
    private javax.swing.JLabel passText1;
    private javax.swing.JSeparator separator;
    private javax.swing.JSeparator separator1;
    private javax.swing.JPanel signInButton;
    private javax.swing.JLabel signInLabel;
    private javax.swing.JLabel signInText;
    private javax.swing.JLabel textSignUp;
    private javax.swing.JLabel textWarning;
    private javax.swing.JLabel userText;
    // End of variables declaration//GEN-END:variables
}
